# -*- coding: utf-8 -*-
"""AI_Smart_Medical_wegoo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MKMjKJZ0Si5LYY0Y6txM2XbJ44NwhlUP
"""

import pandas as pd
import numpy as np

df = pd.read_csv("diabetes_prediction_dataset .csv")
df.head()

df.tail()

df_zero = df[df['diabetes'] == 0]
rows_to_drop = df_zero.sample(n=64049, random_state=42).index
df_new = df.drop(rows_to_drop)
print("Before:", df.shape)
print("After:", df_new.shape)
df_new.to_csv('cleaned_dataset.csv', index=False)

df_new = df.drop(rows_to_drop)

df = df_new.copy()

df_new.to_csv('cleaned_dataset.csv', index=False)

df = pd.read_csv('cleaned_dataset.csv')

print(df.shape)

df.tail()

df.shape

df.info()

df.describe().T

df.isnull().sum()

df.duplicated().sum()

df["diabetes"].value_counts()

df["diabetes"].value_counts(normalize=True) * 100

print("Statistical Summary:")
df.describe().T

categorical_cols = ["gender", "smoking_history"]

for col in categorical_cols:
    print(f"\nValue counts for {col}:")
    print(df[col].value_counts())

print("Unique values in each column:")
for col in df.columns:
    print(col, ":", df[col].nunique())

numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Numerical columns:")
print(numerical_cols)

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x="diabetes", data=df)
plt.title("Diabetes Distribution")
plt.show()

sns.histplot(df["age"], bins=30, kde=True)
plt.title("Age Distribution")
plt.show()

sns.boxplot(x="diabetes", y="age", data=df)
plt.title("Age vs Diabetes")
plt.show()

sns.boxplot(x="diabetes", y="bmi", data=df)
plt.title("BMI vs Diabetes")
plt.show()

sns.boxplot(x="diabetes", y="HbA1c_level", data=df)
plt.title("HbA1c vs Diabetes")
plt.show()

sns.boxplot(x="diabetes", y="blood_glucose_level", data=df)
plt.title("Glucose vs Diabetes")
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

sns.countplot(x="smoking_history", hue="diabetes", data=df)
plt.xticks(rotation=45)
plt.title("Smoking vs Diabetes")
plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["gender"] = le.fit_transform(df["gender"])
df["smoking_history"] = le.fit_transform(df["smoking_history"])

X = df.drop("diabetes", axis=1)
y = df["diabetes"]

from sklearn.model_selection import train_test_split

# Drop rows where 'diabetes' is NaN before splitting
df_cleaned = df.dropna(subset=['diabetes'])
X = df_cleaned.drop("diabetes", axis=1)
y = df_cleaned["diabetes"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

y_prob = xgb_model.predict_proba(X_test)[:,1]

# جرّب كذا threshold
threshold = 0.3
y_pred = (y_prob > threshold).astype(int)

xgb = XGBClassifier(scale_pos_weight=2)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced"),

    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric='logloss'
    )
}



from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score

results = []

for name, model in models.items():


    if name == "Logistic Regression":
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        y_prob = model.predict_proba(X_test_scaled)[:,1]
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:,1]

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)

    results.append([name, acc, prec, rec, auc])

import pandas as pd

results_df = pd.DataFrame(
    results,
    columns=["Model", "Accuracy", "Precision", "Recall", "ROC-AUC"]
)

print(results_df.sort_values(by="ROC-AUC", ascending=False))

xgb_model = models["XGBoost"]

import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": xgb_model.feature_importances_
})

feature_importance = feature_importance.sort_values(by="Importance", ascending=False)

print(feature_importance)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.barh(feature_importance["Feature"], feature_importance["Importance"])
plt.gca().invert_yaxis()
plt.title("Feature Importance (XGBoost)")
plt.show()

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
import pandas as pd

# Reuse the 'models' dictionary that already contains the trained models
# The 'models' dictionary was defined in EDshTR42Vtcz and trained in jRM8OS9cWXXN

results = []

for name, m in models.items():
    if name == "Logistic Regression":
        y_pred = m.predict(X_test_scaled)
        y_prob = m.predict_proba(X_test_scaled)[:,1]
    else:
        y_pred = m.predict(X_test)
        y_prob = m.predict_proba(X_test)[:,1] # Get probabilities for ROC AUC

    acc = accuracy_score(y_test, y_pred)
    roc = roc_auc_score(y_test, y_prob) # Use y_prob for ROC AUC

    print(f"\n📌 Model: {name}")
    print("Accuracy:", acc)
    print("ROC AUC:", roc)
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

    results.append([name, acc, roc])

# جدول مقارنة
results_df = pd.DataFrame(results, columns=["Model", "Accuracy", "ROC AUC"])
print("\n📊 Comparison Table:")
print(results_df)

from sklearn.model_selection import cross_val_score

for name, m in models.items():
    scores = cross_val_score(m, X, y, cv=5, scoring='roc_auc')
    print(f"\n{name} CV ROC AUC:", scores.mean())

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

for name, m in models.items():
    y_prob = m.predict_proba(X_test)[:,1]
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    plt.plot(fpr, tpr, label=name)

plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

from sklearn.model_selection import RandomizedSearchCV

params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3,5,7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1]
}

search = RandomizedSearchCV(
    XGBClassifier(),
    params,
    scoring='recall',
    cv=3,
    n_iter=10
)

search.fit(X_train, y_train)

best_model = search.best_estimator_

print("Best Parameters:")
print(search.best_params_)

from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, accuracy_score

y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))

print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
fn = cm[1][0]
print("False Negatives:", fn)

print("Old FN: 170")
print("New FN:", fn)

y_prob = best_model.predict_proba(X_test)[:,1]

y_pred = (y_prob > 0.3).astype(int)

from sklearn.metrics import confusion_matrix, recall_score

cm = confusion_matrix(y_test, y_pred)
fn = cm[1][0]
recall = recall_score(y_test, y_pred)

print("Recall:", recall)
print("False Negatives:", fn)

fp = cm[0][1]
print("False Positives:", fp)

import joblib

joblib.dump(best_model, "diabetes_model.pkl")

model = joblib.load("diabetes_model.pkl")

joblib.dump(scaler, "scaler.pkl")

joblib.dump(le, "encoder.pkl")

joblib.dump({
    "model": best_model,
    "scaler": scaler
}, "full_pipeline.pkl")

data = joblib.load("full_pipeline.pkl")

model = data["model"]
scaler = data["scaler"]

